test_that(".tree_get_list", {
    tree_list <- .tree_get_list(myClim::mc_data_example_raw)
    expect_equal(names(tree_list$A1E05), c("1_91184101", "2_92201058"))
    expect_equal(names(tree_list$A1E05$`1_91184101`), "Thermo_T")
    tree_list <- .tree_get_list(myClim::mc_data_example_agg)
    expect_equal(names(tree_list$A1E05), c("Thermo_T", "Dendro_T", "Dendro_raw"))
})

test_that(".tree_filter_data", {
    selected_raw <- readRDS("../data/tree/selected_raw.rds")
    filtered_raw_data <- .tree_filter_data(myClim::mc_data_example_raw, selected_raw)
    expect_equal(length(filtered_raw_data$localities), 2)
    expect_equal(length(filtered_raw_data$localities$A1E05$loggers), 2)
    expect_equal(length(filtered_raw_data$localities$A1E05$loggers[[1]]$sensors), 1)
    expect_equal(length(filtered_raw_data$localities$A1E05$loggers[[2]]$sensors), 2)
    expect_equal(length(filtered_raw_data$localities$A2E32$loggers), 1)
    expect_equal(length(filtered_raw_data$localities$A2E32$loggers[[1]]$sensors), 4)
    selected_agg <- readRDS("../data/tree/selected_agg.rds")
    filtered_agg_data <- .tree_filter_data(myClim::mc_data_example_agg, selected_agg)
    expect_equal(length(filtered_agg_data$localities), 2)
    expect_equal(length(filtered_agg_data$localities$A1E05$sensors), 3)
    expect_equal(length(filtered_agg_data$localities$A2E32$sensors), 4)
})

test_that(".tree_selected_to_vector", {
    selected_raw <- readRDS("../data/tree/selected_raw.rds")
    selected_items <- .tree_selected_to_vector(selected_raw)
    expect_equal(length(selected_items), 11)
    selected_agg <- readRDS("../data/tree/selected_agg.rds")
    selected_items <- .tree_selected_to_vector(selected_agg)
    expect_equal(length(selected_items), 8)
})
