test_that("test shiny clean object", {
    app <- shinytest2::AppDriver$new(.app_get_shiny_object(myClim::mc_data_example_clean))
    app$set_inputs(facet_select = "locality")
    app$set_inputs(date_range = c("2020-11-01", "2021-02-01"))
    app$set_inputs(date_range = c("2020-11-01", "2020-11-30"))
    app$click("reset_button")
    app$set_inputs(facet_select = "physical")
    app$set_inputs(data_loggers = "A2E32: TMS")
    app$set_inputs(settings_checkboxes = "color_by_logger")
    app$set_inputs(settings_checkboxes = c("plotly", "color_by_logger"))
    app$set_inputs(settings_checkboxes = "color_by_logger")
    app$set_inputs(settings_checkboxes = c("multi_select", "color_by_logger"))
    app$set_inputs(sensor_select = "TMS_T1")
    app$click("refresh_button")
    app$set_inputs(navbar_page = "States")
    app$set_inputs(states_use_plotly_checkbox = TRUE)
    app$set_inputs(states_use_plotly_checkbox = FALSE)
    app$set_inputs(navbar_page = "Data")
    app$stop()
    expect_true(TRUE)
})

test_that("test shiny agg object", {
    app <- shinytest2::AppDriver$new(.app_get_shiny_object(myClim::mc_data_example_agg))
    app$set_inputs(facet_select = "locality")
    app$set_inputs(date_range = c("2020-11-01", "2021-02-01"))
    app$set_inputs(date_range = c("2020-11-01", "2020-11-30"))
    app$click("reset_button")
    app$set_inputs(facet_select = "physical")
    app$set_inputs(data_loggers = "A2E32")
    app$set_inputs(settings_checkboxes = "color_by_logger")
    app$set_inputs(settings_checkboxes = c("plotly", "color_by_logger"))
    app$set_inputs(settings_checkboxes = "color_by_logger")
    app$set_inputs(settings_checkboxes = c("multi_select", "color_by_logger"))
    app$set_inputs(sensor_select = "TMS_T1")
    app$click("refresh_button")
    app$set_inputs(navbar_page = "States")
    app$set_inputs(states_use_plotly_checkbox = TRUE)
    app$set_inputs(states_use_plotly_checkbox = FALSE)
    app$set_inputs(navbar_page = "Data")
    app$stop()
    expect_true(TRUE)
})