# common
.texts_cancel <- "Cancel"
.texts_clear <- "Clear"
.texts_create <- "Create"
.texts_delete <- "Delete"
.texts_edit <- "Edit"
.texts_end_date <- "End date"
.texts_end_time <- "End time"
.texts_new <- "New"
.texts_select <- "Select"
.texts_selected_semicolon <- "Selected: "
.texts_start_date <- "Start date"
.texts_start_time <- "Start time"
.texts_tag <- "Tag"
.texts_unchanged <- "Unchanged"
.texts_value <- "Value"

# plot
.texts_plot_no_tag <- "No visible tag"
.texts_plot_no_tag_value <- " "
.texts_plot_filter_by_plot <- "Filter by plot"
.texts_plot_index_x <- "index as x"
.texts_plot_multi_localities_error <- "In uncleaned raw data, only one locality can be selected."

# states
.texts_states_delete_states_question <- "Delete {count_states} states?"
.texts_states_empty_tag_notification <- "The tag value is required!"
.texts_states_new_states <- "New state"
.texts_states_new_states_warning <- "WARNING: Adding a new state will apply it to all sensors selected in the Plot section."
.texts_states_not_correct_range_notification <- "The date range isn't selected correctly!"
.texts_states_not_selected_states_notification <- "There isn't selected any state!"
.texts_states_not_selected_range <- "There isn't selected date range!"
.texts_states_save_button <- "Save states"
.texts_states_file_saved <- "States saved to {input$file_states_textinput}"

# data
.texts_data_delete <- "Delete selected"
.texts_data_restore <- "Restore selected"
.texts_data_multi_loggers_error <- "In uncleaned raw data, only one logger can be selected."
.texts_data_save_button <- "Save delete table"
.texts_data_file_saved <- "Delete table saved to {input$file_delete_textinput}"